[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION = "9.4.0"
  REACT_APP_PROD_KOVAN_ARBITRATOR_ADDRESS = "0x381F5C07529f1d0f8D3A7394a7448218e316eA80"
  REACT_APP_PROD_RINKEBY_ARBITRATOR_ADDRESS = "0x27a836a66a16d10a4d5a400dd89417e4e9a8961f"
  REACT_APP_DEV_KOVAN_ARBITRABLE_ADDRESS = "0x9371EDc79662E299a5EAbb687c4ec150915eCD38"
  REACT_APP_ARBITRATOR_EXTRADATA = "0"
  REACT_APP_ARBITRATOR_TIMEOUT = "172800"
  REACT_APP_PROD_STORE_PROVIDER = "https://develop.kleros.in"
  REACT_APP_DEV_STORE_AWS_PROVIDER = "https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
  YARN_FLAGS = "--no-ignore-optional"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
    NODE_VERSION = "9.4.0"
    REACT_APP_PROD_KOVAN_ARBITRATOR_ADDRESS = "0x6183694b0f853dff99cde9ad322973ac580b2127"
    REACT_APP_PROD_RINKEBY_ARBITRATOR_ADDRESS = "0xcafa054b1b054581faf65adce667bf1c684b6ef0"
    REACT_APP_PROD_KOVAN_ARBITRABLE_ADDRESS = "0x9371EDc79662E299a5EAbb687c4ec150915eCD38"
    REACT_APP_ARBITRATOR_EXTRADATA = "0"
    REACT_APP_ARBITRATOR_TIMEOUT = "172800"
    REACT_APP_PROD_STORE_PROVIDER = "https://kleros.in"
    REACT_APP_PROD_STORE_AWS_PROVIDER = "https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/cfs"
    YARN_FLAGS = "--no-ignore-optional"
